FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY installasi.txt .
RUN pip install --no-cache-dir -r installasi.txt

COPY . .

CMD ["sh", "-c", "python simulator/gps-bus-simulator.py & python simulator/passenger-counter-simulator.py & wait"]
